version: '3.1'

services:
  db:
    image: mysql
    container_name: banking_api_db2
    environment:
      MYSQL_DATABASE: banking_api_db2
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3306:3306"

