version: '3.1'

services:
  db:
    image: mysql
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: banking_api_db2
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3306:3306"
    volumes:
      - banking_api_db2_data:/var/lib/mysql
  db_test:
    image: mysql
    container_name: mysql_test_container
    environment:
      MYSQL_DATABASE: banking_test_db
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3307:3306"
    volumes:
      - banking_test_db_data:/var/lib/mysql

  cache:
    image: redis
    restart: always
    ports:
      - '6379:6379'

volumes:
  banking_api_db2_data:
  banking_test_db_data:

